imports:
    - { resource: "@RdvFrontEndBundle/Resources/config/security.yml" }


# app/config/security.yml
security:
    role_hierarchy:
        ROLE_ADMIN: [ROLE_PATIENT, ROLE_OPTICIEN , ROLE_PROFESSIONNEL]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
    firewalls:
            dev:
                pattern:  ^/(_(profiler|wdt)|css|images|js)/
                security: false

            # Firewall pour les pages de connexion, inscription, et récupération de mot de passe

            main:
                pattern: ^/
                form_login:                     # On définit notre méthode d'authentification
                    provider:    fos_userbundle # On lit l'authentification au provider définit plus haut
                    login_path:  /login
                    default_target_path: /
                    remember_me: true           # On active la possibilité du "Se souvenir de moi" (désactivé par
                remember_me:
                    key:         %secret%       # On définit la clé pour le remember_me (%secret% est un parametre
                anonymous:       true           # On autorise les utilisateurs anonymes (non identifiés)
                logout:
                    path: /deconnexion
                    target: /