imports:
    - { resource: "@RdvFrontEndBundle/Resources/config/security.yml" }


# app/config/security.yml
security:
    role_hierarchy:
        ROLE_ADMIN: [ROLE_PATIENT, ROLE_OPTICIEN , ROLE_PROFESSIONNEL]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }


