rdv_front_end_homepage:
    path:     /
    defaults: { _controller: RdvFrontEndBundle:Default:index }

rdv_front_end_test:
    path:     /test
    defaults: { _controller: RdvFrontEndBundle:Default:test }

#Se faire inscrire par Opticien, Patient, Professionel
rdv_front_end_patient:
    path:     /patient/login
    defaults: { _controller: RdvFrontEndBundle:Default:patient }
rdv_front_end_login:
    path:     /login
    defaults: { _controller: RdvFrontEndBundle:Default:login }
rdv_front_end_opticien:
    path:     /opticien/login
    defaults: { _controller: RdvFrontEndBundle:Default:opticien }

rdv_front_end_professionnel:
    path:     /professionnel/login
    defaults: { _controller: RdvFrontEndBundle:Default:professionel }

#Envoyer un mail
rdv_front_end_sendmail:
    path:     /sendmail
    defaults: { _controller: RdvFrontEndBundle:Default:sendMail }