fos_user_profile_show:
    pattern: /
    defaults : { _controller :FOSUserBundle:Profile:show }
    condition: "1 == 0"
    requirements:
        _method: GET
fos_user_profile_edit:
    pattern: /edit
    defaults : { _controller :FOSUserBundle:Profile:edit }
    condition: "1 == 0"
    requirements:
        _method: GET|POST