<?php

namespace Rdv\FrontEndBundle\Repository;

/**
 * OpticienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpticienRepository extends \Doctrine\ORM\EntityRepository
{
}
